CV_Builder/MVC_Project/Models/Experience.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Final.Models
{
    public class Experience
    {
        public int Id { get; set; }
        [DisplayName("Company Name")]
        public string? CompanyName { get; set; }
        [DisplayName("Job Title")]
        public string? JobTitle { get; set;}
        [DataType(DataType.Date)]
        [DisplayName("Start Date")]
        public DateTime StartDate { get; set;}
        [DataType(DataType.Date)]
        [DisplayName("End Date")]
        public DateTime EndDate { get; set;}
        public string? Details  { get; set;}
        public bool isDeleted { get; set; }
    }
}

CV_Builder/MVC_Project/Models/Links.cs
using System.ComponentModel.DataAnnotations;

namespace Final.Models
{
    public class Links
    {
        public Links() { }
        public int Id { get; set; }
    // [RegularExpression ("(?:https?:)?\\/\\/(?:[\\w]+\\.)?linkedin\\.com\\/in\\/(P<permalink>[\\w\\-]+)\\/?")]
        public string Linkedin { get; set; }
    // [RegularExpression("^(http(s?):\\/\\/)?(www\\.)?github\\.([a-z])+\\/([A-Za-z0-9]{1,})+\\/?$")]
        public string GitHub { get; set; }
        public bool isDeleted { get; set; }
    }
}

CV_Builder/MVC_Project/Models/PersonalInfo.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Final.Models
{
    public class PersonalInfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Address { get; set; }
        [RegularExpression ("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")]
        public string Email { get; set; }
        [RegularExpression("^01[0125][0-9]{8}$")]
        public string Phone { get; set; }
        public string Photo { get; set; }
        public string Languages { get; set; }
        [DisplayName("Job Title")]
        public string JobTitle { get; set; }
        public bool isDeleted { get; set; }
    }
}

CV_Builder/MVC_Project/Models/Project.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Final.Models
{
    public class Project
    {
        public int Id { get; set; }
        public string? Title { get; set; }
        public string? Description { get; set; }
        [DataType (DataType.Date)]
        [DisplayName("End Date")]
        public DateTime EndDate { get; set; }
        public string? Link { get; set; }
        public bool isDeleted { get; set; }

    }
}

CV_Builder/MVC_Project/Models/Skill.cs
using System.ComponentModel.DataAnnotations;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;

namespace Final.Models
{
    public class Skill
    {

        public int Id { get; set; }
        
        public string? Name { get; set; }
        [Range(20, 100)]
        public int? Level { get; set; }
        public bool isDeleted { get; set; }
    }
}

CV_Builder/MVC_Project/Models/UserData.cs
using System.ComponentModel;
using System.Runtime.Serialization;

namespace Final.Models
{
    public class UserData
    {
        public int Id { get; set; }
        public PersonalInfo PersonalInfo { get; set; } = new PersonalInfo() { };
        [DisplayName("Cover Letter")]
        public string CoverLetter { get; set; }
        
        public virtual List<Skill> Skill { get; set; } =new List<Skill>() { new Skill() { }, new Skill() { }, new Skill() { }, new Skill() { }, new Skill() { }, new Skill() { } };
        public virtual List<Experience> Experiences { get; set; }= new List<Experience>() {new Experience() { },new Experience() { },new Experience() { }  };
        public virtual List<Project> Projects { get; set; }= new List<Project>() {new Project() { },new Project() { },new Project() { }};
        public virtual Links Links { get; set; } = new Links() { };
        public List<CvTemplate> templates { get; set; } = new List<CvTemplate>() { };
        public bool isDeleted { get; set; }
    }
}

CV_Builder/MVC_Project/Controllers/UserDataController.cs
using Final.Models;
using Final.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.VisualBasic.Syntax;
using Microsoft.EntityFrameworkCore;

namespace Final.Controllers
{
    public class UserDataController : Controller
    {
      
        Context context = new Context();

        UserData UserData = new UserData();


        [HttpGet]
        [Authorize]
        public IActionResult PersonalInfo()
        {
          
            
            return View();
        }


        [HttpPost]
        [Authorize]
        public IActionResult CoverLetter(PersonalViewModel ps )
        {

            
                string FileName = ps.Photo.FileName;



                var imagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/clients", FileName);


                ps.Photo.CopyTo(new FileStream(imagePath, FileMode.Create));

                UserData.PersonalInfo.Address = ps.Address;
                UserData.PersonalInfo.Name = ps.Name;
                UserData.PersonalInfo.Age = ps.Age;
                UserData.PersonalInfo.Email = ps.Email;
                UserData.PersonalInfo.JobTitle = ps.JobTitle;
                UserData.PersonalInfo.Languages = ps.Languages;
                UserData.PersonalInfo.Phone = ps.Phone;
                UserData.PersonalInfo.Photo = ps.Photo.FileName;




                return View(UserData);
           
           
              
            
         
        }


        [HttpPost]
        [Authorize]
        public IActionResult Skill(UserData userDataa)
        {
           
                UserData.CoverLetter = userDataa.CoverLetter;



                UserData.PersonalInfo = userDataa.PersonalInfo;


                return View(UserData);
        

          
        }


        [HttpPost]
        [Authorize]
        public IActionResult Experience(UserData userDataa)
        {
           

                UserData.Skill = userDataa.Skill;
                UserData.CoverLetter = userDataa.CoverLetter;
                UserData.PersonalInfo = userDataa.PersonalInfo;
          

            return View(UserData);
        }


        [HttpPost]
        [Authorize]
        public IActionResult Project(UserData userDataa)
        { 
      
                UserData.Experiences = userDataa.Experiences;

                UserData.Skill = userDataa.Skill;
                UserData.CoverLetter = userDataa.CoverLetter;
                UserData.PersonalInfo = userDataa.PersonalInfo;
            

            return View(UserData);
        }


        [HttpPost]
        [Authorize]
        public IActionResult Link(UserData userDataa)
        {
           
                UserData.Projects = userDataa.Projects;

                UserData.Experiences = userDataa.Experiences;
            

                UserData.Skill = userDataa.Skill;
                UserData.CoverLetter = userDataa.CoverLetter;
                UserData.PersonalInfo = userDataa.PersonalInfo;
            
            return View(UserData);
        }
        [HttpPost, Authorize]
        public IActionResult createCv(UserData userDataa)
        {
            if (ModelState.IsValid == true)
            {
                UserData.Links = userDataa.Links;

                UserData.Projects = userDataa.Projects;

                UserData.Experiences = userDataa.Experiences;

                UserData.Skill = userDataa.Skill;
                UserData.CoverLetter = userDataa.CoverLetter;
                UserData.PersonalInfo = userDataa.PersonalInfo;

                ViewData["img"] = userDataa.PersonalInfo.Photo;

                context.UserData.Add(UserData);
                context.SaveChanges();

            
            }
            return View("SliderLayout", userDataa);
        }
    }
}

CV_Builder/MVC_Project/Views/UserData/CoverLetter.cshtml
@using Final.ViewModel;
@model UserData

@{
    Layout = "_UserDataLayout";
    ViewData["Title"] = "CoverLetter";
}

<h1>Objectives</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Skill" asp-controller="UserData" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*cover letter*@
            <div class="form-group">
                <label asp-for="CoverLetter" class="control-label" style="font-size: 25px;width:200px"></label>
                <textarea style="height: 140px;width: 450px;font-size: 21px;" asp-for="CoverLetter" class="form-control"></textarea>
                <span asp-validation-for="CoverLetter" class="text-danger"></span>
            </div>
            @*personal info*@
            <div class="form-group">
                
                <input hidden type="text" value="@Model.PersonalInfo.Address" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Address" class="form-control"></input>

            </div>
            <div class="form-group">

                <input hidden type="text" value="@Model.PersonalInfo.Age" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Age" class="form-control"></input>

            </div>
            <div class="form-group">

                <input hidden type="text" value="@Model.PersonalInfo.Languages" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Languages" class="form-control"></input>

            </div>
            <div class="form-group">
                
                <input hidden type="text" value="@Model.PersonalInfo.Phone" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Phone" class="form-control"></input>

            </div>
            <div class="form-group">
                
                <input hidden type="text" value="@Model.PersonalInfo.Photo" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Photo" class="form-control"></input>

            </div>
            <div class="form-group">
                
                <input hidden type="text" value="@Model.PersonalInfo.Name" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Name" class="form-control"></input>

            </div>
            <div class="form-group">
                
                <input hidden type="text" value="@Model.PersonalInfo.Email" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Email" class="form-control"></input>
                
            </div>
            <div class="form-group">
                
                <input hidden type="text" value="@Model.PersonalInfo.JobTitle" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.JobTitle" class="form-control"></input>

            </div>
            
            
            <div class="form-group">
                <br />
                <input type="submit" value="Next" name="submit" class="btn " style="background-color:#eb5d1e;color:white" />
          
            
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CV_Builder/MVC_Project/Views/UserData/Experience.cshtml
@using Final.ViewModel;
@model UserData

@{
    Layout = "_UserDataLayout";
    ViewData["Title"] = "Experience";
}

<h1 style="margin-top: -55px;">Experience</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Project" asp-controller="UserData" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            
        @*experience*@

                @for (int i = 0; i < Model.Experiences.Count; i++)
                {

                    
                        <div style="width:490px;border:3px solid #eb5d1e;border-radius:15px;padding:10px; margin:8px;">
             <div class="form-group ">
                    <label asp-for="@Model.Experiences[i].CompanyName" class="control-label" style="width:200px;font-size: 25px;"></label>
                    <input asp-for="@Model.Experiences[i].CompanyName" class="form-control" style="width:250px;font-size: 21px;" />
                    <span asp-validation-for="@Model.Experiences[i].CompanyName" class="text-danger"></span>
            </div>
                        <div class="form-group ">
                    <label asp-for="@Model.Experiences[i].JobTitle" class="control-label" style="font-size: 25px;"></label>
                    <input asp-for="@Model.Experiences[i].JobTitle" class="form-control" style="width:250px;font-size: 21px;" />
                    <span asp-validation-for="@Model.Experiences[i].JobTitle" class="text-danger"></span>
            </div>
                        <div class="form-group ">
                    <label asp-for="@Model.Experiences[i].StartDate" class="control-label" style="font-size: 25px;"></label>
                    <input asp-for="@Model.Experiences[i].StartDate" class="form-control" style="width:250px;font-size: 21px;" />
                    <span asp-validation-for="@Model.Experiences[i].StartDate" class="text-danger"></span>
            </div>
            <div class="form-group ">
                    <label asp-for="@Model.Experiences[i].EndDate" class="control-label" style="font-size: 25px;"></label>
                    <input asp-for="@Model.Experiences[i].EndDate" class="form-control" style="width:250px;font-size: 21px;" />
                    <span asp-validation-for="@Model.Experiences[i].EndDate" class="text-danger"></span>
            </div>
                        <div class="form-group">
                    <label asp-for="@Model.Experiences[i].Details" class="control-label" style="font-size: 25px;"></label>
                    <textarea asp-for="@Model.Experiences[i].Details" class="form-control" style="height: 140px;width: 450px;font-size: 21px;"></textarea>
                    <span asp-validation-for="@Model.Experiences[i].Details" class="text-danger"></span>
            </div>
            </div>
           
            }
            @*personal info*@
            <div class="form-group">

                <input hidden type="text" value="@Model.PersonalInfo.Address" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Address" class="form-control"></input>

            </div>
            <div class="form-group">

                <input hidden type="text" value="@Model.PersonalInfo.Age" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Age" class="form-control"></input>

            </div>
            <div class="form-group">

                <input hidden type="text" value="@Model.PersonalInfo.Languages" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Languages" class="form-control"></input>

            </div>
            <div class="form-group">

                <input hidden type="text" value="@Model.PersonalInfo.Phone" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Phone" class="form-control"></input>

            </div>
            <div class="form-group">

                <input hidden type="text" value="@Model.PersonalInfo.Photo" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Photo" class="form-control"></input>

            </div>
            <div class="form-group">

                <input hidden type="text" value="@Model.PersonalInfo.Name" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Name" class="form-control"></input>

            </div>
            <div class="form-group">

                <input hidden type="text" value="@Model.PersonalInfo.Email" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Email" class="form-control"></input>

            </div>
            <div class="form-group">

                <input hidden type="text" value="@Model.PersonalInfo.JobTitle" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.JobTitle" class="form-control"></input>

            </div>
            @* cover letter*@
            <div class="form-group">
                <textarea hidden value="@Model.CoverLetter" style="height: 140px;width: 450px;" asp-for="@Model.CoverLetter" class="form-control"></textarea>

            </div>
          
           @* skills*@
            @for (int i=0; i<Model.Skill.Count; i++)
                {

                 
                    <div class="form-group ">

                    <input hidden value="@Model.Skill[i].Name" asp-for="@Model.Skill[i].Name" id="SkillName" class="form-control" style="width:100%" />
                            
                    </div>

                    <div class="form-group ">

                    <input hidden value="@Model.Skill[i].Level" asp-for="@Model.Skill[i].Level" type="range" min="20" max="100" step="20" style="width:100%" />
                            
                    </div>
                    
          
                 
                }



            <div class="form-group">
                <br />

                <input type="submit" value="Next" class="btn " style="background-color:#eb5d1e;color:white" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
   
  }

CV_Builder/MVC_Project/Views/UserData/Link.cshtml
@using Final.ViewModel;
@model UserData

@{
    Layout = "_UserDataLayout";
    ViewData["Title"] = "Link";
}

<h1>Links</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="createCv" asp-controller="UserData" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
          @*  links*@
            <div class="form-group">
                <label asp-for="@Model.Links.Linkedin" class="control-label" style="font-size: 25px;"></label>
                <input asp-for="@Model.Links.Linkedin" class="form-control" style="width:400px;font-size: 21px;" />
                <span asp-validation-for="@Model.Links.Linkedin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Links.GitHub" class="control-label" style="font-size: 25px;"></label>
                <input asp-for="@Model.Links.GitHub" class="form-control" style="width:400px;font-size: 21px;" />
                <span asp-validation-for="@Model.Links.GitHub" class="text-danger"></span>
            </div>

            
            @*personal info*@
            <div class="form-group">

                <input hidden type="text" value="@Model.PersonalInfo.Address" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Address" class="form-control"/>

            </div>
            <div class="form-group">

                <input hidden type="text" value="@Model.PersonalInfo.Age" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Age" class="form-control"/>

            </div>
            <div class="form-group">

                <input hidden type="text" value="@Model.PersonalInfo.Languages" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Languages" class="form-control"/>

            </div>
            <div class="form-group">

                <input hidden type="text" value="@Model.PersonalInfo.Phone" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Phone" class="form-control"/>

            </div>
            <div class="form-group">

                <input hidden type="text" value="@Model.PersonalInfo.Photo" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Photo" class="form-control"/>

            </div>
            <div class="form-group">

                <input hidden type="text" value="@Model.PersonalInfo.Name" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Name" class="form-control"/>

            </div>
            <div class="form-group">

                <input hidden type="text" value="@Model.PersonalInfo.Email" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Email" class="form-control"/>

            </div>
            <div class="form-group">

                <input hidden type="text" value="@Model.PersonalInfo.JobTitle" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.JobTitle" class="form-control"/>

            </div>
            @* cover letter*@
            <div class="form-group">
                <textarea hidden value="@Model.CoverLetter" style="height: 140px;width: 450px;" asp-for="@Model.CoverLetter" class="form-control"></textarea>

            </div>

            @* skills*@
            @for (int i = 0; i < Model.Skill.Count; i++)
            {


                <div class="form-group ">

                    <input hidden value="@Model.Skill[i].Name" asp-for="@Model.Skill[i].Name" id="SkillName" class="form-control" style="width:100%" />

                </div>

                <div class="form-group ">

                    <input hidden value="@Model.Skill[i].Level" asp-for="@Model.Skill[i].Level" type="range" min="20" max="100" step="20" style="width:100%" />

                </div>



            }
            @* experience*@
            @for (int i = 0; i < Model.Experiences.Count; i++)
            {
                <div class="form-group ">
                    <input hidden value="@Model.Experiences[i].CompanyName" asp-for="@Model.Experiences[i].CompanyName" class="form-control" style="width:250px" />
                </div>
                <div class="form-group ">
                    <input hidden value="@Model.Experiences[i].JobTitle" asp-for="@Model.Experiences[i].JobTitle" class="form-control" style="width:250px" />
                </div>
                <div class="form-group ">
                    <input hidden value="@Model.Experiences[i].StartDate" asp-for="@Model.Experiences[i].StartDate" class="form-control" style="width:250px" />
                </div>
                <div class="form-group ">
                    <input hidden value="@Model.Experiences[i].EndDate" asp-for="@Model.Experiences[i].EndDate" class="form-control" style="width:250px" />
                </div>
                <div class="form-group">
                    <textarea hidden value="@Model.Experiences[i].Details" asp-for="@Model.Experiences[i].Details" class="form-control" style="height: 140px;width: 450px;"></textarea>
                </div>

            }

            @*projects*@
            @for (int i = 0; i < Model.Projects.Count; i++)
            {
                <div class="form-group">
                    <input hidden value="@Model.Projects[i].Title" asp-for="@Model.Projects[i].Title" class="form-control"  style="width:250px">
                </div>
                <div class="form-group">
                    <textarea hidden value="@Model.Projects[i].Description" asp-for="@Model.Projects[i].Description" class="form-control" style="height: 140px;width: 450px;"></textarea>
                </div>
                <div class="form-group">
                    <input hidden value="@Model.Projects[i].EndDate" asp-for="@Model.Projects[i].EndDate" class="form-control" style="width:250px" />
                </div>
                <div class="form-group">
                  
                    <input hidden value="@Model.Projects[i].Link" asp-for="@Model.Projects[i].Link" class="form-control" style="width:250px" />
                </div>


            }
           
            <div class="form-group">
                <br />
                <input type="submit" value="Next" class="btn " style="background-color:#eb5d1e;color:white" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CV_Builder/MVC_Project/Views/UserData/PersonalInfo.cshtml
@using Final.ViewModel;
@model PersonalViewModel

@{
    Layout = "_UserDataLayout";
    ViewData["Title"] = "PersonalInfo";
}

<h1 style="width:600px;margin-top: -55px;">Personal Information</h1>
<hr />

<div class="row" style="height:auto">
    <div class="col-md-4" style="height:auto">
        <form asp-action="coverLetter" asp-controller="UserData" style="height:auto" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger" ></div>

            @*personalinfo*@
            <div class="form-group">
                <label asp-for="@Model.Name" class="control-label" style="font-size: 25px;"></label>
                <input asp-for="@Model.Name" class="form-control" style="width:250px;font-size: 21px;" />
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Age" class="control-label" style="font-size: 25px;"></label>
                <input asp-for="@Model.Age" class="form-control" style="width:250px;font-size: 21px;" />
                <span asp-validation-for="@Model.Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Address" class="control-label" style="font-size: 25px;"></label>
                <input asp-for="@Model.Address" class="form-control" style="width:250px;font-size: 21px;" />
                <span asp-validation-for="@Model.Address" class="text-danger"></span>
            </div>

             <div class="form-group">
                <label asp-for="@Model.Email" class="control-label" style="font-size: 25px;"></label>
                <input asp-for="@Model.Email" class="form-control" style="width:250px;font-size: 21px;" />
                <span asp-validation-for="@Model.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Phone" class="control-label" style="font-size: 25px;"></label>
                <input asp-for="@Model.Phone" class="form-control" style="width:250px;font-size: 21px;" />
                <span asp-validation-for="@Model.Phone" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.Photo" class="control-label" style="font-size: 25px;"></label>
                <input asp-for="@Model.Photo" type="file" class="form-control" style="width:250px;font-size: 21px;" />
                <span asp-validation-for="@Model.Photo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Languages" class="control-label" style="font-size: 25px;"></label>
                <input asp-for="@Model.Languages" class="form-control" style="width:250px;font-size: 21px;" />
                <span asp-validation-for="@Model.Languages" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.JobTitle" class="control-label" style="font-size: 25px;"></label>
                <input asp-for="@Model.JobTitle" class="form-control" style="width:250px;font-size: 21px;" />
                <span asp-validation-for="@Model.JobTitle" class="text-danger"></span>
            </div>
   
            <div class="form-group">
                <br />
                <input type="submit" value="Next" class="btn " style="background-color:#eb5d1e;color:white" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CV_Builder/MVC_Project/Views/UserData/Skill.cshtml
@using Final.ViewModel;
@model UserData

@{
    Layout = "_UserDataLayout";
    ViewData["Title"] = "Skill";
}

<h1 style="margin-top: -55px;">Skills</h1>
<hr />
<div class="row">
    <div class="col-md-12"style="height:auto" >
      
           
        <form asp-action="Experience" asp-controller="UserData">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="d-flex flex-wrap" id="RadioBtn">
           @* skills*@
          
             @for (int i=0; i<Model.Skill.Count(); i++)
                {

                    <div class="col-md-6 flex-wrap" >

                        <div style="border:3px solid #eb5d1e;border-radius:15px;padding:4px; margin:5px;">
                            <div class="form-group col-md-6">
                            <label asp-for="@Model.Skill[i].Name" class="control-label" style="font-size: 25px;"></label>
                            <input asp-for="@Model.Skill[i].Name" id="SkillName" class="form-control" style="width:100%;font-size: 21px;" />
                            <span asp-validation-for="@Model.Skill[i].Name" class="text-danger"></span>
                               </div>

                    <div class="form-group col-md-6" style="padding:20px 0;">
                            <label asp-for="@Model.Skill[i].Level" class="control-label" style="font-size: 25px;"></label>
                            <input asp-for="@Model.Skill[i].Level" type="range" min="20" max="100" step="20" style="width:100%;font-size: 21px;" />
                            <span asp-validation-for="@Model.Skill[i].Level" class="text-danger"></span>
                              </div>
                    
                       </div>   
          
                   </div>
               
                }

                @*personal info*@
                <div class="form-group">

                    <input hidden type="text" value="@Model.PersonalInfo.Address" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Address" class="form-control"></input>

                </div>
                <div class="form-group">

                    <input hidden type="text" value="@Model.PersonalInfo.Age" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Age" class="form-control"></input>

                </div>
                <div class="form-group">

                    <input hidden type="text" value="@Model.PersonalInfo.Languages" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Languages" class="form-control"></input>

                </div>
                <div class="form-group">

                    <input hidden type="text" value="@Model.PersonalInfo.Phone" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Phone" class="form-control"></input>

                </div>
                <div class="form-group">

                    <input hidden type="text" value="@Model.PersonalInfo.Photo" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Photo" class="form-control"></input>

                </div>
                <div class="form-group">

                    <input hidden type="text" value="@Model.PersonalInfo.Name" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Name" class="form-control"></input>

                </div>
                <div class="form-group">

                    <input hidden type="text" value="@Model.PersonalInfo.Email" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.Email" class="form-control"></input>

                </div>
                <div class="form-group">

                    <input hidden type="text" value="@Model.PersonalInfo.JobTitle" style="height: 140px;width: 450px;" asp-for="@Model.PersonalInfo.JobTitle" class="form-control"></input>

                </div>
               @* cover letter*@
                <div class="form-group">
                    <textarea hidden value="@Model.CoverLetter" style="height: 140px;width: 450px;" asp-for="@Model.CoverLetter" class="form-control"></textarea>

                </div>
                
  
            <div class="form-group">
                <br />

                    <input type="submit" value="Next" class="btn " style="background-color:#eb5d1e;color:white" />
            </div>
            </div>
        </form>
       
        
    </div>

</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}